# Generated by Django 5.1.4 on 2025-02-13 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='products.product'),
        ),
    ]
