# Generated by Django 5.1.4 on 2025-02-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_couponusage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
