# Generated by Django 5.1.4 on 2025-02-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_couponusage_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='allow_multiple_use',
            field=models.BooleanField(default=False, help_text='Allow users to use this coupon multiple times'),
        ),
    ]
