# Generated by Django 5.1.4 on 2025-01-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsizecolor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
