# Generated by Django 5.1.4 on 2025-02-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_razorpay_order_id_order_razorpay_payment_id'),
        ('products', '0002_productsizecolor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
            preserve_default=False,
        ),
    ]
