# Generated by Django 5.1.4 on 2025-02-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
